### PR TITLE
feat: change homepage

### PR DESCRIPTION
**Pull request by admbtlr**

### CODE REVIEW

**Review by MartijnR — CHANGES_REQUESTED** [review]
Great. Thanks!

1. ~~Should the "Visit DSFSG" link be removed for now?~~ looks like an 'Under Construction" site will be up
2. Tweak menu to show only top-level History and Blog perhaps?
3. Remove social media links in footer (clearing accounts in _config.yml)

Let me if you are stretched for time, and I can just merge and make these tweaks afterwards.

**Comment by admbtlr** [comment]
Hmm, this is odd: I've pushed more commits to the [feat/change-homepage](https://github.com/DSFSG/opendatakit.org/tree/feat/change-homepage) branch, but they're not showing up on this PR.

Maybe I should try re-opening the PR? But then we'd lose the comment history. Any ideas @MartijnR?

**Comment by MartijnR** [comment]
That's very odd indeed. Some temporary GitHub issue probably. I do actually see 2 additional commits (4 in total) at my local machine. So if those are all the commits we should be good! I'll merge locally.

**Comment by MartijnR** [comment]
Looks great. Merged by 9ee78c57989995d2019d9def598254c44dc541f7

**Pull request closed without merging**
